Facebook Android included potentially causing weird build error Error CS0234: The type or namespace name `XamlFilePathAttribute' does not exist in the namespace `Xamarin.Forms.Xaml'. Are you missing an assembly reference?